
name: HerokuCICD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        env:
          HEROKU_DOCKER_KEY: ${{ secrets.HEROKU_DOCKER_KEY }}
        run: docker login --username jeremyy.demlow@gmail.com -p ${HEROKU_DOCKER_KEY} registry.heroku.com
      - name: Docker Build
        run: |
              echo registry.heroku.com/jeremydemlowdjangoblog/web
              docker build -t registry.heroku.com/jeremydemlowdjangoblog/web .
      - name: Push Docker Image
        run: |
              docker push registry.heroku.com/jeremydemlowdjangoblog/web

  # deploys to heroku via a docker container deployment
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "jeremydemlowdjangoblog"
          heroku_email: "jeremy.demlow@gmail.com"
          usedocker: true